import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DEFAULT_POLICY, SIGNAL_ORDER, SIGNAL_SPECS, formatINR, formatINRCompact, hashObject } from '@kreaton/core';
import type { ModelSpec, SignalGroup, SignalId } from '@kreaton/core';
import { ARTEFACTS, DATA_DIR, writeText } from '../paths.js';
import type { FullMetrics } from '../metrics.js';
import type { PortfolioReport } from '../report.js';

/**
 * Render docs/MODEL_CARD.md from the committed artefacts.
 *
 * The card is generated rather than written so that every number in it is
 * the number in model.json, fit.json, metrics.json and adversarial.json. Run
 * after `seed`, `evaluate` and `adversarial`.
 */

interface Fit {
  modelVersion: string;
  corpus: { totalTransactions: number; fraudulentTransactions: number; observedFraudRate: number; byTypology: Record<string, { count: number }> };
  split: { splitAtMs: number; trainRows: number; testRows: number };
  diagnostics: {
    groupCorrelation: Record<SignalGroup, number>;
    irlsIterations: number;
    irlsConverged: boolean;
    trainFraud: number;
    filledBins: Array<{ signal: SignalId; bin: number }>;
    marginalAuc: Record<SignalId, number>;
  };
}

interface Metrics {
  generatedAt: string;
  heldOut: FullMetrics;
  recovery: { atReportLag: number; quantiles: { p10: number; p50: number; p90: number }; estimatorGap: { maxAbsDiff: number; atMinutes: number } };
  portfolio: PortfolioReport;
  auditChainValid: boolean;
}

interface Adversarial {
  episodesPerAttack: number;
  policyPreset?: { id: string; label: string };
  calibration: { referenceFpr: number };
  defences: Record<string, { label: string }>;
  results: Array<{ label: string; byDefence: Record<string, { rate: number; interval: { lo: number; hi: number } }>; ablation: { improvementPp: number; significant: boolean } }>;
  summary: Record<string, { caught: number; episodes: number; leaked: number }>;
}

const pct = (x: number, d = 1) => `${(x * 100).toFixed(d)}%`;
const read = <T,>(path: string): T => JSON.parse(readFileSync(path, 'utf8')) as T;

function main(): void {
  const model = read<ModelSpec>(ARTEFACTS.model);
  const fit = read<Fit>(ARTEFACTS.fit);
  const metrics = read<Metrics>(ARTEFACTS.metrics);
  const adv = read<Adversarial>(ARTEFACTS.adversarial);
  const digest = hashObject(model);
  const d = fit.diagnostics;
  const r = metrics.portfolio;
  const L: string[] = [];
  const push = (s = '') => L.push(s);

  push('# Model card');
  push();
  push(`**Model** ${model.version} · fitted ${model.fittedAt.slice(0, 10)} · digest \`${digest.slice(0, 16)}\``);
  push(`**Author** Team Kreaton · generated by \`npm run modelcard\` on ${new Date().toISOString().slice(0, 10)}`);
  push();
  push('## What it is');
  push();
  push(
    'A real-time scorer and decision engine for authorised push payment (APP) fraud on UPI-style rails. Twelve behavioural, beneficiary-side and session-context signals are each discretised and mapped to a fitted log-likelihood ratio; the ratios are weighted, discounted for within-group correlation, floored where an attacker controls the evidence, summed in log-odds, and mapped to a calibrated probability by isotonic regression. The probability and the amount price three actions (approve, hold for out-of-band re-confirmation, block) by expected cost, and the cheapest is taken. Every decision is sealed into a hash-chained audit ledger with the full evidence table.',
  );
  push();
  push('## Intended use and limits');
  push();
  push('- Screens push payments at authorisation time for a sending payment service provider. Not a beneficiary-side or post-settlement tool.');
  push('- Fitted and evaluated on a typology-grounded synthetic corpus, reproducible from the seed. No figure below is a measurement of live UPI traffic, and the model card says so wherever a number depends on an assumption.');
  push('- Beneficiary intelligence (onward velocity, confirmed-mule linkage) is a supplied input, standing in for network-level or inter-institution sharing. Without such a feed the payee-graph group loses most of its power; the PaySim cross-validation shows what remains.');
  push('- The default policy prices are documented estimates. `docs/SENSITIVITY.md` reports which of them the boundary actually depends on.');
  push();
  push('## Training data');
  push();
  push(`| | |`);
  push(`| --- | ---: |`);
  push(`| Payments in corpus | ${fit.corpus.totalTransactions.toLocaleString('en-IN')} |`);
  push(`| Fraudulent | ${fit.corpus.fraudulentTransactions.toLocaleString('en-IN')} (${pct(fit.corpus.observedFraudRate, 2)}) |`);
  push(`| Chronological split | ${fit.split.trainRows.toLocaleString('en-IN')} train / ${fit.split.testRows.toLocaleString('en-IN')} test, cut at ${new Date(fit.split.splitAtMs).toISOString().slice(0, 10)} |`);
  push(`| Fraud in training window | ${d.trainFraud} |`);
  push(`| Typologies | ${Object.entries(fit.corpus.byTypology).sort((a, b) => b[1].count - a[1].count).map(([t, v]) => `${t} (${v.count})`).join(', ')} |`);
  push();
  push('The split is by time, never at random: the model is fitted on the past and judged on a future that contains mule networks it never saw. Beneficiary intelligence is applied on its own delayed timeline during feature extraction, so a payment is never scored with knowledge that arrived after it.');
  push();
  push('## Held-out performance');
  push();
  push('| Metric | Value |');
  push('| --- | ---: |');
  push(`| ROC AUC | ${model.metrics.rocAuc.toFixed(4)} |`);
  push(`| PR AUC | ${model.metrics.prAuc.toFixed(4)} (prevalence ${pct(fit.corpus.observedFraudRate, 2)}) |`);
  push(`| KS | ${model.metrics.ks.toFixed(4)} |`);
  push(`| Brier | ${model.metrics.brier.toFixed(6)} |`);
  push(`| Expected calibration error | ${model.metrics.ece.toFixed(4)} (worst bin ${metrics.heldOut.calibration.mce.toFixed(4)}) |`);
  push(`| Recall at 1% FPR | ${pct(model.metrics.recallAt1PctFpr)} |`);
  push();
  push('Recall at a false-positive ceiling, from the scorer alone:');
  push();
  push('| FPR ceiling | Recall | Value recall | Precision |');
  push('| ---: | ---: | ---: | ---: |');
  for (const op of metrics.heldOut.operatingPoints) {
    push(`| ${pct(op.maxFpr, op.maxFpr < 0.01 ? 1 : 0)} | ${pct(op.point.recall)} | ${pct(op.valueRecall)} | ${pct(op.point.precision)} |`);
  }
  push();
  push('## Signals');
  push();
  push('Weights are fitted by penalised maximum likelihood (IRLS, ridge centred on one). Standalone AUC is reported as a guard against the corpus: the evaluation fails if any signal exceeds 0.98 alone, because on generated data that is how a leak presents.');
  push();
  push('| Signal | Group | Weight | Shrinkage | LLR range | Alone AUC |');
  push('| --- | --- | ---: | ---: | ---: | ---: |');
  for (const id of SIGNAL_ORDER) {
    const spec = SIGNAL_SPECS[id];
    const woe = model.signals.find((s) => s.id === id)!;
    push(
      `| ${spec.label} | ${spec.group} | ${woe.weight.toFixed(3)} | ${model.groupShrinkage[spec.group].toFixed(3)} | ${Math.min(...woe.llrByBin).toFixed(2)} to ${Math.max(...woe.llrByBin).toFixed(2)} | ${d.marginalAuc[id].toFixed(3)} |`,
    );
  }
  push();
  for (const id of SIGNAL_ORDER) {
    const spec = SIGNAL_SPECS[id];
    push(`### ${spec.label}`);
    push();
    push(`*${spec.description}* Unit: ${spec.unit}. Bin edges: ${spec.binEdges.join(', ')}. Reason code prefix \`${spec.reasonCodePrefix}\`.`);
    push();
    push(spec.rationale);
    push();
  }
  push('## Fusion');
  push();
  push(`Base rate ${pct(model.baseRate, 3)} (prior log-odds ${Math.log(model.baseRate / (1 - model.baseRate)).toFixed(3)}). Intra-group correlation, estimated on the training window and applied as a per-group discount when several signals in the group fire together:`);
  push();
  push('| Group | ρ |');
  push('| --- | ---: |');
  for (const [g, rho] of Object.entries(d.groupCorrelation)) push(`| ${g} | ${rho.toFixed(3)} |`);
  push();
  push(`Asymmetric evidence: total negative contribution from the \`${model.asymmetricEvidence.cappedGroups.join('`, `')}\` group is floored at ${model.asymmetricEvidence.negativeFloor.toFixed(2)} nats. Presence of a coercion indicator costs an attacker something; absence costs nothing and is therefore not allowed to argue for the payment without limit.`);
  push();
  if (d.filledBins.length > 0) {
    push(`${d.filledBins.length} bins were never observed in training and were filled from their nearest observed neighbour: ${d.filledBins.map((b) => `${b.signal}[${b.bin}]`).join(', ')}.`);
    push();
  }
  push('## Calibration');
  push();
  push(`Isotonic regression (pool-adjacent-violators) on the training window, compressed to ${model.calibration.length} knots kept where the level moves rather than at even ranks. Held-out reliability:`);
  push();
  push('| Predicted | Observed | Payments |');
  push('| ---: | ---: | ---: |');
  for (const b of metrics.heldOut.calibration.bins.filter((x) => x.count > 0)) {
    push(`| ${pct(b.meanPredicted, 3)} | ${pct(b.observedRate, 3)} | ${b.count.toLocaleString('en-IN')} |`);
  }
  push();
  push('## Recoverability');
  push();
  push(`Mule chain survival is modelled two ways, a continuous-time Markov chain in closed form and a lognormal-dwell Monte Carlo with per-layer traceability; the Monte Carlo drives decisions and the two disagree by at most ${pct(metrics.recovery.estimatorGap.maxAbsDiff)} (at ${metrics.recovery.estimatorGap.atMinutes} min). Time to full cash-out: p10 ${metrics.recovery.quantiles.p10.toFixed(0)} min, median ${metrics.recovery.quantiles.p50.toFixed(0)} min, p90 ${metrics.recovery.quantiles.p90.toFixed(0)} min. At the default report lag of ${DEFAULT_POLICY.reportLagMinutes} min plus ${DEFAULT_POLICY.freezeLatencyMinutes} min freeze latency, ${pct(metrics.recovery.atReportLag)} of value remains freezable.`);
  push();
  push('| Layer | Median dwell (min) | Hops onward | Reachable |');
  push('| ---: | ---: | ---: | ---: |');
  model.recovery.layerDwellMinutes.forEach((dwell, i) => {
    push(`| ${i + 1} | ${dwell} | ${pct(model.recovery.hopProbability[i] ?? 0, 0)} | ${pct(model.recovery.traceabilityByLayer[i] ?? 0, 0)} |`);
  });
  push();
  push('These parameters are documented estimates; see `docs/MODELING.md` for the reasoning behind each.');
  push();
  push('## Decisions on the held-out window');
  push();
  push(`Full interceptor replay under the default policy, ${r.screened.count.toLocaleString('en-IN')} payments (${formatINRCompact(r.screened.valuePaise)}):`);
  push();
  push('| | |');
  push('| --- | ---: |');
  push(`| Approved / held / blocked | ${r.byAction.APPROVE.count.toLocaleString('en-IN')} / ${r.byAction.STEP_UP.count.toLocaleString('en-IN')} / ${r.byAction.BLOCK.count.toLocaleString('en-IN')} |`);
  push(`| Detection | ${pct(r.outcomes.detectionRate)} by count, ${pct(r.outcomes.valueDetectionRate)} by value |`);
  push(`| False-positive rate | ${pct(r.outcomes.falsePositiveRate, 2)} of legitimate payments |`);
  push(`| Precision at corpus prevalence | ${pct(r.outcomes.precision)} |`);
  push(`| Compensation liability avoided | ${formatINR(r.financial.liabilityAvoidedPaise)} of ${formatINR(r.financial.unmitigatedLiabilityPaise)} unmitigated |`);
  push(`| Friction cost | ${formatINR(r.financial.frictionCostPaise)} |`);
  push(`| Net benefit | ${formatINR(r.financial.netBenefitPaise)} |`);
  push(`| Authorisation latency | mean ${r.latency.meanMs.toFixed(3)} ms, p99 ${r.latency.p99Ms.toFixed(3)} ms |`);
  push(`| Audit chain | ${metrics.auditChainValid ? 'verified intact' : 'BROKEN'} |`);
  push();
  push('Detection by typology, weakest first:');
  push();
  push('| Typology | Cases | By count | By value |');
  push('| --- | ---: | ---: | ---: |');
  for (const t of [...r.byTypology].sort((a, b) => a.detectionRate - b.detectionRate)) {
    push(`| ${t.typology} | ${t.count} | ${pct(t.detectionRate)} | ${pct(t.valueDetectionRate)} |`);
  }
  push();
  push('## Adversarial evaluation');
  push();
  push(`${adv.results.length} attacks, ${adv.episodesPerAttack} episodes each, against three defences calibrated to interrupt ${pct(adv.calibration.referenceFpr, 2)} of legitimate payments. An episode counts as caught when any payment in it is held or blocked.`);
  push();
  push(`| Attack | ${Object.values(adv.defences).map((x) => x.label).join(' | ')} | Ablation |`);
  push(`| --- | ${Object.keys(adv.defences).map(() => '---:').join(' | ')} | ---: |`);
  for (const res of adv.results) {
    push(`| ${res.label} | ${Object.keys(adv.defences).map((k) => `${pct(res.byDefence[k]!.rate)} [${pct(res.byDefence[k]!.interval.lo, 0)}–${pct(res.byDefence[k]!.interval.hi, 0)}]`).join(' | ')} | ${res.ablation.improvementPp >= 0 ? '+' : ''}${res.ablation.improvementPp.toFixed(1)} pp${res.ablation.significant ? '' : ' (n.s.)'} |`);
  }
  push();
  push(`Overall: ${Object.entries(adv.summary).map(([k, v]) => `${adv.defences[k]!.label} ${pct(v.caught / v.episodes)} (leaked ${formatINRCompact(v.leaked)})`).join('; ')}.`);
  push();
  const lfPath = resolve(DATA_DIR, 'adversarial-liability_first.json');
  if (existsSync(lfPath)) {
    const lf = read<Adversarial>(lfPath);
    push(`Under the ${lf.policyPreset?.label ?? 'liability-first'} preset, which re-prices friction and raises the matched budget to ${pct(lf.calibration.referenceFpr, 2)} of legitimate payments, the full system catches ${pct(lf.summary.expected_cost!.caught / lf.summary.expected_cost!.episodes)} of attacked episodes against ${pct(lf.summary.rule_baseline!.caught / lf.summary.rule_baseline!.episodes)} for the rule, and leaks ${formatINRCompact(lf.summary.expected_cost!.leaked)}. The stance is the lever for the weak positions; the console's adversarial page shows both side by side.`);
    push();
  }
  push('## Known weaknesses');
  push();
  const weakest = [...r.byTypology].sort((a, b) => a.detectionRate - b.detectionRate)[0]!;
  const weakestAttack = [...adv.results].sort((a, b) => a.byDefence.expected_cost!.rate - b.byDefence.expected_cost!.rate)[0]!;
  push(`- Weakest typology: ${weakest.typology} at ${pct(weakest.detectionRate)} by count. A willing payer, a plausible amount and no coercion indicators leave only the beneficiary side.`);
  push(`- Weakest adversarial position: ${weakestAttack.label} at ${pct(weakestAttack.byDefence.expected_cost!.rate)} caught.`);
  push(`- The default policy is conservative: ${pct(r.outcomes.falsePositiveRate, 2)} of legitimate payments interrupted, ${pct(r.outcomes.detectionRate)} of fraud caught by count. The balanced prices are documented estimates, and under them the expected-cost minimum sits at low friction. The policy studio, the presets and the constraint solver exist to move along the frontier explicitly; the sensitivity table shows which prices move it.`);
  push('- Beneficiary intelligence was available at decision time for a small minority of payments, by construction of the delayed timeline. The model does not depend on it, but it is the signal with the most headroom in deployment.');
  push('- Synthetic corpus. Three generator artefacts that produced perfect single-signal separation were found and removed during the build (`docs/MODELING.md`); the single-signal guard remains in the evaluation and the CI gate so a fourth cannot pass unnoticed.');
  push();

  writeText(ARTEFACTS.modelCard, L.join('\n'));
  console.log(`Wrote ${ARTEFACTS.modelCard}`);
}

main();
