import { toPaise } from '@kreaton/core';
import type { Paise, Typology, VpaEntryMethod } from '@kreaton/core';

/**
 * Scam typologies and their behavioural fingerprints.
 *
 * This file is the substantive content of the generated corpus. Fraud is not
 * modelled as a random label sprinkled over transactions: each fraudulent
 * payment is produced by one of eight documented scam types, and each type has
 * a distinct observable fingerprint because the social engineering that drives
 * it is distinct.
 *
 * That distinction is what makes the evaluation meaningful. If fraud were
 * generated by perturbing a few fields at random, a detector would be measuring
 * its ability to find the perturbation rather than its ability to find fraud,
 * and every reported metric would be circular. Here, the contextual signals have
 * to earn their discrimination against eight genuinely different patterns, some
 * of which, notably marketplace purchase scams, are deliberately hard.
 *
 * On provenance, stated plainly: the typology set and the relative shares
 * reflect the pattern of authorised push payment fraud reported publicly in
 * India, where task-based job scams and investment scams dominate by volume and
 * value respectively and coercive impersonation, the so-called digital arrest,
 * produces the largest individual losses. The specific distribution parameters
 * are calibrated estimates chosen to produce realistic marginals, not
 * measurements from proprietary data. docs/MODELING.md records the reasoning
 * per parameter and reports how sensitive the results are to each.
 */

export interface TypologySpec {
  id: Typology;
  label: string;
  /** Share of all fraudulent payments. Shares sum to 1. */
  share: number;
  /** What the scam is, in a sentence. */
  description: string;
  /** Why the fingerprint below looks the way it does. */
  fingerprint: string;

  /** Amount drawn lognormally in paise log space. */
  amountLogMean: number;
  amountLogSd: number;
  amountFloor: Paise;
  amountCeiling: Paise;

  /** Probability a call is in progress at authorisation. */
  activeCallProb: number;
  /** Mean call duration at authorisation, in seconds. */
  callSecondsMean: number;
  screenShareProb: number;
  remoteAccessProb: number;

  /** Mean in-session application switches before authorisation. */
  appSwitchMean: number;
  /** Mean seconds from app open to authorisation. */
  authorizeSecondsMean: number;
  entryMix: Record<VpaEntryMethod, number>;

  /** Probability the payer is steered to keep amounts under a threshold. */
  structuringProb: number;
  /** Probability the payment is made from an unrecognised device. */
  newDeviceProb: number;

  /** Relative hour-of-day weights over IST, reflecting the operator schedule. */
  hourWeights: number[];
  /** Payments extracted from one victim in a single episode. */
  episodeMin: number;
  episodeMax: number;
  /**
   * Probability that a later episode against the same victim reuses a
   * collection account they have already paid.
   *
   * This is what stops beneficiary novelty from becoming a proxy for the label.
   * Several typologies involve a sustained relationship in which the victim
   * pays the same account repeatedly over weeks: a romance scam runs on one
   * trusted counterparty, and an investment scam keeps the victim depositing to
   * the same platform account. By the third payment that beneficiary is no
   * longer new, and a system that relies on novelty alone has already stopped
   * seeing it.
   */
  repeatBeneficiaryProb: number;
}

/** Uniform weights, for typologies with no strong time preference. */
const FLAT = new Array<number>(24).fill(1);

/** Weighted toward office hours, when impersonating an institution is credible. */
const OFFICE_HOURS = [
  0.2, 0.1, 0.1, 0.1, 0.2, 0.4, 0.8, 1.4, 2.2, 3.0, 3.4, 3.2, 2.6, 3.0, 3.4, 3.2, 2.8, 2.2,
  1.6, 1.2, 0.9, 0.7, 0.5, 0.3,
];

/** Weighted toward evenings and late nights, when victims are alone. */
const EVENING = [
  0.8, 0.6, 0.4, 0.3, 0.3, 0.3, 0.4, 0.6, 0.9, 1.1, 1.2, 1.3, 1.3, 1.4, 1.5, 1.7, 2.0, 2.6,
  3.2, 3.6, 3.4, 2.8, 2.0, 1.3,
];

/** Spread across the whole day, including hours a bank branch is unreachable. */
const ROUND_CLOCK = [
  1.4, 1.3, 1.2, 1.0, 0.9, 0.8, 0.9, 1.1, 1.4, 1.7, 1.8, 1.8, 1.7, 1.8, 1.9, 1.9, 1.8, 1.7,
  1.6, 1.6, 1.6, 1.6, 1.5, 1.4,
];

export const TYPOLOGIES: readonly TypologySpec[] = [
  {
    id: 'digital_arrest',
    label: 'Digital arrest',
    share: 0.14,
    description:
      'The victim is told by a caller posing as police, customs or a central agency that they are under investigation, kept on a video or voice call for hours, and instructed to transfer funds for verification.',
    fingerprint:
      'The longest calls of any typology and the largest single losses. The victim is held on the line through the entire payment, often with the screen shared so the caller can watch them comply. Payments run around the clock because the coercion script depends on preventing the victim from consulting anyone.',
    amountLogMean: Math.log(toPaise(250_000)),
    amountLogSd: 1.0,
    amountFloor: toPaise(20_000),
    amountCeiling: toPaise(4_000_000),
    activeCallProb: 0.97,
    callSecondsMean: 4_200,
    screenShareProb: 0.55,
    remoteAccessProb: 0.18,
    appSwitchMean: 2.2,
    authorizeSecondsMean: 95,
    entryMix: { typed: 0.3, pasted: 0.55, qr: 0.02, contact: 0.03, deeplink: 0.1 },
    structuringProb: 0.28,
    newDeviceProb: 0.04,
    hourWeights: ROUND_CLOCK,
    episodeMin: 1,
    episodeMax: 5,
    repeatBeneficiaryProb: 0.18,
  },
  {
    id: 'investment_trading',
    label: 'Investment and trading',
    share: 0.21,
    description:
      'The victim is recruited into a fake trading or pre-IPO allocation platform that shows fabricated gains, then asked for progressively larger deposits and eventually for fees to release withdrawals.',
    fingerprint:
      'Large amounts and heavy application switching, because the victim is moving between the fake platform and their banking app to copy account details. Calls are less common than in coercive typologies: the pressure is greed and sunk cost rather than fear, so the relationship runs over chat.',
    amountLogMean: Math.log(toPaise(120_000)),
    amountLogSd: 1.2,
    amountFloor: toPaise(5_000),
    amountCeiling: toPaise(5_000_000),
    activeCallProb: 0.35,
    callSecondsMean: 700,
    screenShareProb: 0.15,
    remoteAccessProb: 0.05,
    appSwitchMean: 5.4,
    authorizeSecondsMean: 55,
    entryMix: { typed: 0.18, pasted: 0.66, qr: 0.02, contact: 0.02, deeplink: 0.12 },
    structuringProb: 0.34,
    newDeviceProb: 0.03,
    hourWeights: EVENING,
    episodeMin: 2,
    episodeMax: 9,
    repeatBeneficiaryProb: 0.55,
  },
  {
    id: 'job_task',
    label: 'Task-based job scam',
    share: 0.16,
    description:
      'The victim is offered paid work completing simple tasks, receives small genuine payouts, then is required to deposit their own funds to unlock higher-paying task sets.',
    fingerprint:
      'The highest volume and the smallest amounts, which makes it the typology where a fixed risk threshold performs worst and the amount-dependent decision boundary earns its place. Extremely high application switching, because instructions arrive continuously over a messaging group.',
    amountLogMean: Math.log(toPaise(8_000)),
    amountLogSd: 1.1,
    amountFloor: toPaise(500),
    amountCeiling: toPaise(300_000),
    activeCallProb: 0.15,
    callSecondsMean: 300,
    screenShareProb: 0.04,
    remoteAccessProb: 0.02,
    appSwitchMean: 7.1,
    authorizeSecondsMean: 28,
    entryMix: { typed: 0.12, pasted: 0.62, qr: 0.06, contact: 0.02, deeplink: 0.18 },
    structuringProb: 0.42,
    newDeviceProb: 0.02,
    hourWeights: EVENING,
    episodeMin: 3,
    episodeMax: 14,
    repeatBeneficiaryProb: 0.42,
  },
  {
    id: 'kyc_update',
    label: 'KYC or account update',
    share: 0.13,
    description:
      'The victim is warned that their account, SIM or payment credential will be suspended unless they complete an urgent verification, which is steered into a payment or a remote-access session.',
    fingerprint:
      'The typology most associated with remote-access tooling: the caller talks the victim into installing a screen-sharing application in order to help them complete the update. Office-hours weighted, because impersonating a bank is only credible when a bank would plausibly call.',
    amountLogMean: Math.log(toPaise(35_000)),
    amountLogSd: 0.9,
    amountFloor: toPaise(1_000),
    amountCeiling: toPaise(900_000),
    activeCallProb: 0.88,
    callSecondsMean: 950,
    screenShareProb: 0.3,
    remoteAccessProb: 0.45,
    appSwitchMean: 3.3,
    authorizeSecondsMean: 42,
    entryMix: { typed: 0.22, pasted: 0.48, qr: 0.04, contact: 0.02, deeplink: 0.24 },
    structuringProb: 0.2,
    newDeviceProb: 0.12,
    hourWeights: OFFICE_HOURS,
    episodeMin: 1,
    episodeMax: 4,
    repeatBeneficiaryProb: 0.1,
  },
  {
    id: 'refund_reversal',
    label: 'Refund and reversal',
    share: 0.11,
    description:
      'The victim is told a refund, subsidy or mistaken credit needs to be returned or re-processed, and is walked through a payment presented as a reversal.',
    fingerprint:
      'Near-universal concurrent calls and the heaviest use of remote-access software, since the script depends on the caller appearing to drive the refund themselves. Amounts are moderate and often deliberately odd, to look like a genuine reversal.',
    amountLogMean: Math.log(toPaise(15_000)),
    amountLogSd: 0.9,
    amountFloor: toPaise(500),
    amountCeiling: toPaise(400_000),
    activeCallProb: 0.92,
    callSecondsMean: 780,
    screenShareProb: 0.22,
    remoteAccessProb: 0.6,
    appSwitchMean: 2.6,
    authorizeSecondsMean: 38,
    entryMix: { typed: 0.2, pasted: 0.5, qr: 0.08, contact: 0.02, deeplink: 0.2 },
    structuringProb: 0.18,
    newDeviceProb: 0.06,
    hourWeights: OFFICE_HOURS,
    episodeMin: 1,
    episodeMax: 3,
    repeatBeneficiaryProb: 0.08,
  },
  {
    id: 'purchase_marketplace',
    label: 'Marketplace purchase',
    share: 0.13,
    description:
      'The victim pays for goods advertised on a classifieds or social marketplace that are never delivered, often through a collect request framed as a deposit or delivery fee.',
    fingerprint:
      'Deliberately the hardest case in the corpus. Small amounts, a genuinely willing payer, no coercion indicators, and a payment that looks exactly like an ordinary purchase. It exists to stop the evaluation flattering the contextual signals, and detection rates on it are reported separately for that reason.',
    amountLogMean: Math.log(toPaise(4_500)),
    amountLogSd: 0.9,
    amountFloor: toPaise(200),
    amountCeiling: toPaise(150_000),
    activeCallProb: 0.5,
    callSecondsMean: 260,
    screenShareProb: 0.02,
    remoteAccessProb: 0.01,
    appSwitchMean: 2.4,
    authorizeSecondsMean: 66,
    entryMix: { typed: 0.16, pasted: 0.3, qr: 0.28, contact: 0.06, deeplink: 0.2 },
    structuringProb: 0.08,
    newDeviceProb: 0.02,
    hourWeights: FLAT,
    episodeMin: 1,
    episodeMax: 2,
    repeatBeneficiaryProb: 0.06,
  },
  {
    id: 'romance',
    label: 'Romance and trust',
    share: 0.06,
    description:
      'A relationship cultivated over weeks or months is monetised through a manufactured emergency, a customs charge, or an investment the victim is invited to share in.',
    fingerprint:
      'Long grooming means the victim is unhurried and often uses a familiar device, so behavioural signals are weak. What remains detectable is the beneficiary side: the money still lands in the same collection infrastructure as every other typology.',
    amountLogMean: Math.log(toPaise(60_000)),
    amountLogSd: 1.1,
    amountFloor: toPaise(2_000),
    amountCeiling: toPaise(2_000_000),
    activeCallProb: 0.25,
    callSecondsMean: 1_500,
    screenShareProb: 0.03,
    remoteAccessProb: 0.02,
    appSwitchMean: 2.0,
    authorizeSecondsMean: 110,
    entryMix: { typed: 0.3, pasted: 0.5, qr: 0.03, contact: 0.07, deeplink: 0.1 },
    structuringProb: 0.12,
    newDeviceProb: 0.02,
    hourWeights: EVENING,
    episodeMin: 2,
    episodeMax: 8,
    repeatBeneficiaryProb: 0.62,
  },
  {
    id: 'impersonation_known_person',
    label: 'Known-person impersonation',
    share: 0.06,
    description:
      'A message from a compromised or spoofed account of a family member, colleague or superior requests an urgent transfer, frequently with a reason for being unreachable by voice.',
    fingerprint:
      'Rarely involves a call, because the script explicitly avoids one: the pretext is that the sender cannot talk. Heavy application switching between the messaging app and the payment app, fast authorisation, and a pasted identifier. The typology where showing the payer the registered beneficiary name is most decisive.',
    amountLogMean: Math.log(toPaise(12_000)),
    amountLogSd: 0.8,
    amountFloor: toPaise(500),
    amountCeiling: toPaise(500_000),
    activeCallProb: 0.08,
    callSecondsMean: 120,
    screenShareProb: 0.01,
    remoteAccessProb: 0.01,
    appSwitchMean: 6.2,
    authorizeSecondsMean: 22,
    entryMix: { typed: 0.14, pasted: 0.7, qr: 0.02, contact: 0.04, deeplink: 0.1 },
    structuringProb: 0.14,
    newDeviceProb: 0.03,
    hourWeights: OFFICE_HOURS,
    episodeMin: 1,
    episodeMax: 3,
    repeatBeneficiaryProb: 0.12,
  },
] as const;

/** Typology shares, for the weighted draw. */
export const TYPOLOGY_WEIGHTS: Record<Typology, number> = Object.fromEntries(
  TYPOLOGIES.map((t) => [t.id, t.share]),
) as Record<Typology, number>;

export function typologyById(id: Typology): TypologySpec {
  const spec = TYPOLOGIES.find((t) => t.id === id);
  if (!spec) throw new Error(`Unknown typology: ${id}`);
  return spec;
}

/** Guard against the shares drifting out of normalisation when edited. */
export function validateShares(): void {
  const total = TYPOLOGIES.reduce((s, t) => s + t.share, 0);
  if (Math.abs(total - 1) > 1e-9) {
    throw new Error(`Typology shares must sum to 1, got ${total}`);
  }
}
