"""
Sensitivity of the decision boundaries to each policy estimate.

The default policy in packages/core/src/cost.ts is a set of documented
estimates, not measurements. A reviewer is entitled to ask which of them the
decision actually depends on. This script perturbs each one by a quarter in
both directions and reports how far the two closed-form boundaries move at
three reference amounts, then writes the table to docs/SENSITIVITY.md.

The boundary formulas are the ones in cost.ts:

    p1 = (F_su + a_su * CLV) / (A * L * c + a_su * CLV)
    p2 = (F_bl - F_su + (a_bl - a_su) * CLV) / ((1 - c) * A * L + (a_bl - a_su) * CLV)

where A is the amount, L = (1 - recovery) * liabilityShare, and c is the
step-up catch rate. Recovery at the report lag is taken from data/metrics.json,
so the table reflects the fitted recoverability curve rather than a guess.

Usage:
    python analysis/sensitivity.py
"""

from __future__ import annotations

import sys

# Windows consoles default to a legacy code page that cannot print a rupee sign.
sys.stdout.reconfigure(encoding="utf-8")

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METRICS = ROOT / "data" / "metrics.json"
OUT = ROOT / "docs" / "SENSITIVITY.md"

# Mirrors DEFAULT_POLICY in packages/core/src/cost.ts. Paise throughout.
DEFAULT = {
    "liabilityShare": 1.0,
    "stepUpCatchRate": 0.65,
    "stepUpFrictionPaise": 3_500,
    "blockFrictionPaise": 25_000,
    "stepUpAbandonmentRate": 0.04,
    "blockAbandonmentRate": 0.18,
    "customerLifetimeValuePaise": 800_000,
    "reportLagMinutes": 240,
}

LABEL = {
    "liabilityShare": "Liability share",
    "stepUpCatchRate": "Step-up catch rate",
    "stepUpFrictionPaise": "Hold friction",
    "blockFrictionPaise": "Block friction",
    "stepUpAbandonmentRate": "Abandonment after hold",
    "blockAbandonmentRate": "Abandonment after block",
    "customerLifetimeValuePaise": "Lifetime value",
    "recovery": "Recoverable at report lag",
}

AMOUNTS = [(500_000, "₹5,000"), (2_500_000, "₹25,000"), (10_000_000, "₹1,00,000")]


def thresholds(amount: float, recovery: float, p: dict) -> tuple[float, float]:
    per_paise = (1 - min(max(recovery, 0.0), 1.0)) * p["liabilityShare"]
    exposure = amount * per_paise
    clv = p["customerLifetimeValuePaise"]
    c = min(max(p["stepUpCatchRate"], 0.0), 1.0)
    gap = (p["blockAbandonmentRate"] - p["stepUpAbandonmentRate"]) * clv
    su_abandon = p["stepUpAbandonmentRate"] * clv
    d1 = exposure * c + su_abandon
    p1 = (p["stepUpFrictionPaise"] + su_abandon) / d1 if d1 > 0 else 1.0
    d2 = exposure * (1 - c) + gap
    n2 = p["blockFrictionPaise"] - p["stepUpFrictionPaise"] + gap
    p2 = n2 / d2 if d2 > 0 else 1.0
    p1 = min(max(p1, 0.0), 1.0)
    p2 = min(max(p2, 0.0), 1.0)
    return p1, max(p1, p2)


def pct(x: float) -> str:
    if x >= 0.1:
        return f"{x * 100:.1f}%"
    if x >= 0.01:
        return f"{x * 100:.2f}%"
    return f"{x * 100:.3f}%"


def main() -> None:
    metrics = json.loads(METRICS.read_text(encoding="utf8"))
    recovery = float(metrics["recovery"]["atReportLag"])

    lines: list[str] = []
    lines.append("# Sensitivity of the decision boundaries")
    lines.append("")
    lines.append(
        "Generated by `analysis/sensitivity.py` from the default policy and the fitted "
        f"recoverability of {pct(recovery)} at the {DEFAULT['reportLagMinutes']}-minute report lag. "
        "Each estimate is moved a quarter down and a quarter up while the others stay at their defaults; "
        "the cells show where the hold boundary (p1) and the block boundary (p2) land."
    )
    lines.append("")
    lines.append("Baseline:")
    lines.append("")
    lines.append("| Amount | Hold above | Block above |")
    lines.append("| --- | ---: | ---: |")
    for amount, label in AMOUNTS:
        p1, p2 = thresholds(amount, recovery, DEFAULT)
        lines.append(f"| {label} | {pct(p1)} | {pct(p2)} |")
    lines.append("")

    # Elasticity: percentage change in the boundary per percentage change in the input.
    rows: list[tuple[str, float, float]] = []
    for key in list(DEFAULT.keys()) + ["recovery"]:
        if key == "reportLagMinutes":
            continue
        lines.append(f"## {LABEL[key]}")
        lines.append("")
        lines.append("| Amount | −25%: hold / block | baseline | +25%: hold / block |")
        lines.append("| --- | ---: | ---: | ---: |")
        e1 = 0.0
        e2 = 0.0
        for amount, label in AMOUNTS:
            cells = []
            base = thresholds(amount, recovery, DEFAULT)
            for factor in (0.75, 1.25):
                pol = dict(DEFAULT)
                rec = recovery
                if key == "recovery":
                    rec = min(recovery * factor, 1.0)
                    applied = rec / recovery - 1
                else:
                    pol[key] = DEFAULT[key] * factor
                    if key.endswith("Rate") or key == "liabilityShare":
                        pol[key] = min(pol[key], 1.0)
                    applied = pol[key] / DEFAULT[key] - 1
                p1, p2 = thresholds(amount, rec, pol)
                cells.append(f"{pct(p1)} / {pct(p2)}")
                if applied != 0:
                    if base[0] > 0:
                        e1 = max(e1, abs((p1 - base[0]) / base[0]) / abs(applied))
                    if base[1] > 0:
                        e2 = max(e2, abs((p2 - base[1]) / base[1]) / abs(applied))
            lines.append(f"| {label} | {cells[0]} | {pct(base[0])} / {pct(base[1])} | {cells[1]} |")
        rows.append((LABEL[key], e1, e2))
        lines.append("")

    lines.append("## What the boundary depends on")
    lines.append("")
    lines.append("Largest elasticity of each boundary across the three amounts, per input:")
    lines.append("")
    lines.append("| Input | Hold boundary | Block boundary |")
    lines.append("| --- | ---: | ---: |")
    for label, e1, e2 in sorted(rows, key=lambda r: -max(r[1], r[2])):
        lines.append(f"| {label} | {e1:.2f} | {e2:.2f} |")
    lines.append("")
    lines.append(
        "An elasticity of 1 means a 10% error in the estimate moves the boundary by 10%. "
        "The inputs at the top of this table are the ones worth measuring rather than estimating; "
        "the ones at the bottom can be wrong by a wide margin without changing a decision."
    )
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf8")
    print("\n".join(lines))
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
